"""Generated human-facing phase checkpoint documents.

Builds a root-facing reading layer from the canonical per-phase SUMMARY and
VERIFICATION artifacts. The generated outputs are deterministic:

- one ``phase-checkpoints/<phase-dir>.md`` file per phase that has summaries
- one root ``CHECKPOINTS.md`` index covering the whole project

The canonical source of truth remains ``.gpd/phases/.../*-SUMMARY.md`` and
``*-VERIFICATION.md``. This module only derives readable checkpoint notes from
those artifacts.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from functools import cmp_to_key
from pathlib import Path

from pydantic import BaseModel, ConfigDict, Field

from gpd.core.commands import SummaryExtractResult, cmd_summary_extract
from gpd.core.constants import (
    STANDALONE_SUMMARY,
    STANDALONE_VERIFICATION,
    ProjectLayout,
)
from gpd.core.frontmatter import FrontmatterParseError, extract_frontmatter
from gpd.core.observability import instrument_gpd_function
from gpd.core.utils import atomic_write, compare_phase_numbers, safe_read_file

__all__ = [
    "SyncPhaseCheckpointsResult",
    "sync_phase_checkpoints",
]

_GENERATED_HEADER = "<!-- Generated by gpd sync-phase-checkpoints. Do not edit by hand. -->"


class SyncPhaseCheckpointsResult(BaseModel):
    """Report from syncing generated checkpoint artifacts."""

    model_config = ConfigDict(frozen=True)

    generated: bool
    phase_count: int
    checkpoint_dir: str
    root_index: str
    updated_files: list[str] = Field(default_factory=list)
    removed_files: list[str] = Field(default_factory=list)


@dataclass(frozen=True)
class _PhaseSummaryDoc:
    phase_number: str
    phase_title: str
    summary_path: Path
    plan: str
    completed: str
    one_liner: str
    body: str
    provides: list[str]
    summary_extract: SummaryExtractResult


def _title_from_phase_dir(phase_dir_name: str) -> tuple[str, str]:
    prefix, _, slug = phase_dir_name.partition("-")
    title = " ".join(part.capitalize() for part in slug.split("-") if part)
    return prefix or phase_dir_name, title or "Untitled Phase"


def _clean_sentence(text: str) -> str:
    value = " ".join(text.strip().split())
    value = value.strip().strip('"').strip("'")
    if not value:
        return ""
    if value[-1] not in ".!?":
        value += "."
    return value


def _natural_join(items: list[str]) -> str:
    cleaned = [_clean_sentence(item) for item in items if _clean_sentence(item)]
    if not cleaned:
        return ""
    if len(cleaned) == 1:
        return cleaned[0]
    if len(cleaned) == 2:
        return f"{cleaned[0]} {cleaned[1]}"
    return " ".join(cleaned)


def _prefixed_summary(prefix: str, items: list[str], *, limit: int = 3) -> str:
    cleaned = [" ".join(item.strip().split()) for item in items if item.strip()]
    if not cleaned:
        return ""
    trimmed = cleaned[:limit]
    if len(trimmed) == 1:
        summary = trimmed[0]
    elif len(trimmed) == 2:
        summary = f"{trimmed[0]} and {trimmed[1]}"
    else:
        summary = f"{', '.join(trimmed[:-1])}, and {trimmed[-1]}"
    return _clean_sentence(f"{prefix}{summary}")


def _extract_next_step(body: str) -> str:
    compact = " ".join(body.split())
    patterns = (
        r"(The next clean move is [^.]+\.)",
        r"(The next best step is [^.]+\.)",
        r"(The next move is [^.]+\.)",
        r"(The next clean discussion checkpoint is [^.]+\.)",
    )
    for pattern in patterns:
        match = re.search(pattern, compact)
        if match:
            return match.group(1)
    return ""


def _strip_top_heading(body: str) -> str:
    stripped = body.strip()
    return re.sub(r"^# .+\n+", "", stripped, count=1).strip()


def _summary_sort_key(path: Path) -> tuple[int, str]:
    if path.name == STANDALONE_SUMMARY:
        return (1, path.name)
    return (0, path.name)


def _verification_sort_key(path: Path) -> tuple[int, str]:
    if path.name == STANDALONE_VERIFICATION:
        return (1, path.name)
    return (0, path.name)


def _phase_summary_docs(cwd: Path, phase_dir: Path) -> list[_PhaseSummaryDoc]:
    layout = ProjectLayout(cwd)
    docs: list[_PhaseSummaryDoc] = []

    for summary_path in sorted(
        [path for path in phase_dir.iterdir() if path.is_file() and layout.is_summary_file(path.name)],
        key=_summary_sort_key,
    ):
        content = safe_read_file(summary_path)
        if content is None:
            continue
        try:
            frontmatter, body = extract_frontmatter(content)
        except FrontmatterParseError as exc:
            raise ValueError(f"Failed to parse {summary_path.relative_to(cwd)}: {exc}") from exc

        phase_number, phase_title = _title_from_phase_dir(phase_dir.name)
        summary_relpath = summary_path.relative_to(cwd).as_posix()
        extracted = cmd_summary_extract(cwd, summary_relpath)
        raw_dependency_graph = frontmatter.get("dependency-graph")
        if isinstance(raw_dependency_graph, dict):
            raw_provides = raw_dependency_graph.get("provides")
        else:
            raw_provides = frontmatter.get("provides")
        provides = [str(item).strip() for item in raw_provides or [] if str(item).strip()] if isinstance(
            raw_provides, list
        ) else []
        docs.append(
            _PhaseSummaryDoc(
                phase_number=str(frontmatter.get("phase") or phase_number).strip() or phase_number,
                phase_title=phase_title,
                summary_path=summary_path,
                plan=str(frontmatter.get("plan") or "").strip(),
                completed=str(frontmatter.get("completed") or "").strip(),
                one_liner=(extracted.one_liner or "").strip(),
                body=_strip_top_heading(body),
                provides=provides,
                summary_extract=extracted,
            )
        )

    return docs


def _verification_paths(cwd: Path, phase_dir: Path) -> list[str]:
    layout = ProjectLayout(cwd)
    return [
        path.relative_to(cwd).as_posix()
        for path in sorted(
            [candidate for candidate in phase_dir.iterdir() if candidate.is_file() and layout.is_verification_file(candidate.name)],
            key=_verification_sort_key,
        )
    ]


def _render_story_paragraphs(doc: _PhaseSummaryDoc, plan_count: int) -> list[str]:
    paragraphs: list[str] = []
    intro = f"Phase {doc.phase_number} focused on {doc.phase_title.lower()}."
    if doc.completed:
        intro += f" It closed on {doc.completed}."
    if doc.one_liner:
        intro += f" The headline result was straightforward: {_clean_sentence(doc.one_liner)}"
    if plan_count > 1:
        intro += f" This checkpoint reflects the latest of {plan_count} recorded plan summaries for the phase."
    paragraphs.append(intro)

    decisions = [
        _clean_sentence(
            decision.summary if not decision.rationale else f"{decision.summary}: {decision.rationale}"
        )
        for decision in doc.summary_extract.decisions[:4]
    ]
    if decisions:
        paragraphs.append(f"The main project decisions were concrete. {_natural_join(decisions)}")

    provides = _prefixed_summary(
        "In practical terms, this phase now gives the project ",
        doc.provides or doc.summary_extract.affects or doc.summary_extract.key_files or [],
        limit=4,
    )
    if provides:
        paragraphs.append(provides)

    patterns = _natural_join(doc.summary_extract.patterns[:3])
    if patterns:
        paragraphs.append(f"What this phase clarified was simple. {patterns}")

    next_step = _extract_next_step(doc.body)
    if next_step:
        paragraphs.append(next_step)

    return [paragraph for paragraph in paragraphs if paragraph]


def _render_phase_checkpoint(cwd: Path, phase_dir: Path, docs: list[_PhaseSummaryDoc]) -> str:
    latest = docs[-1]
    checkpoint_dir = ProjectLayout(cwd).phase_checkpoints_dir
    verification_paths = _verification_paths(cwd, phase_dir)

    lines: list[str] = [
        _GENERATED_HEADER,
        "",
        f"# Phase {latest.phase_number} Checkpoint",
        "",
        f"_Title: {latest.phase_title}_",
    ]
    if latest.completed:
        lines.append(f"_Completed: {latest.completed}_")
    lines.append("")

    for paragraph in _render_story_paragraphs(latest, len(docs)):
        lines.append(paragraph)
        lines.append("")

    lines.extend(
        [
            "## Read This Phase",
            "",
        ]
    )

    for doc in docs:
        link = os.path.relpath(doc.summary_path, checkpoint_dir)
        label = f"Plan {doc.plan or '?'} summary"
        if doc is latest:
            label = f"Latest summary ({doc.summary_path.name})"
        lines.append(f"- {label}: [{doc.summary_path.name}]({link})")

    for verification_path in verification_paths:
        verification_file = cwd / verification_path
        link = os.path.relpath(verification_file, checkpoint_dir)
        lines.append(f"- Verification: [{verification_file.name}]({link})")

    key_files = list(dict.fromkeys(latest.summary_extract.key_files))
    for key_file in key_files[:5]:
        lines.append(f"- Primary artifact: `{key_file}`")

    lines.extend(
        [
            "",
            "## Detailed Notes",
            "",
        ]
    )

    if latest.body:
        lines.append(latest.body)
        lines.append("")

    if len(docs) > 1:
        lines.extend(
            [
                "## Earlier Plan Notes",
                "",
            ]
        )
        for doc in docs[:-1]:
            link = os.path.relpath(doc.summary_path, checkpoint_dir)
            lines.append(f"### Plan {doc.plan or '?'}")
            lines.append("")
            if doc.one_liner:
                lines.append(_clean_sentence(doc.one_liner))
                lines.append("")
            lines.append(f"Read the full earlier summary here: [{doc.summary_path.name}]({link})")
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _render_root_index(cwd: Path, grouped: list[tuple[Path, list[_PhaseSummaryDoc]]]) -> str:
    lines = [
        _GENERATED_HEADER,
        "",
        "# Phase Checkpoints",
        "",
        "This is the human-facing checkpoint shelf for the project.",
        "Each phase note is generated from the canonical SUMMARY and VERIFICATION artifacts under `.gpd/phases/`.",
        "",
        "Read one checkpoint file when you want the end-of-phase story in plain English.",
        "Use the linked summary and verification artifacts when you want the full underlying record.",
        "",
        "## Phase Index",
        "",
    ]

    layout = ProjectLayout(cwd)
    for phase_dir, docs in grouped:
        latest = docs[-1]
        link = layout.phase_checkpoint_file(phase_dir.name).relative_to(cwd).as_posix()
        line = f"- [Phase {latest.phase_number}: {latest.phase_title}]({link})"
        if latest.one_liner:
            line += f" — {latest.one_liner}"
        lines.append(line)

    lines.append("")
    return "\n".join(lines)


def _write_if_changed(path: Path, content: str) -> bool:
    existing = safe_read_file(path)
    if existing == content:
        return False
    atomic_write(path, content)
    return True


@instrument_gpd_function("checkpoints.sync_phase_checkpoints")
def sync_phase_checkpoints(cwd: Path) -> SyncPhaseCheckpointsResult:
    """Generate the root-facing checkpoint shelf from phase summaries."""
    layout = ProjectLayout(cwd)
    layout.phase_checkpoints_dir.mkdir(parents=True, exist_ok=True)

    grouped: list[tuple[Path, list[_PhaseSummaryDoc]]] = []
    updated_files: list[str] = []
    removed_files: list[str] = []

    if layout.phases_dir.is_dir():
        for phase_dir in sorted(
            [path for path in layout.phases_dir.iterdir() if path.is_dir()],
            key=cmp_to_key(lambda a, b: compare_phase_numbers(a.name, b.name)),
        ):
            docs = _phase_summary_docs(cwd, phase_dir)
            if not docs:
                continue
            grouped.append((phase_dir, docs))
            checkpoint_path = layout.phase_checkpoint_file(phase_dir.name)
            content = _render_phase_checkpoint(cwd, phase_dir, docs)
            if _write_if_changed(checkpoint_path, content):
                updated_files.append(checkpoint_path.relative_to(cwd).as_posix())

    expected_checkpoint_paths = {
        layout.phase_checkpoint_file(phase_dir.name).resolve()
        for phase_dir, _docs in grouped
    }
    for existing in sorted(
        [
            path
            for path in layout.phase_checkpoints_dir.glob("*.md")
            if not path.name.startswith("._")
        ]
    ):
        if existing.resolve() in expected_checkpoint_paths:
            continue
        existing.unlink()
        removed_files.append(existing.relative_to(cwd).as_posix())

    root_content = _render_root_index(cwd, grouped)
    if _write_if_changed(layout.checkpoints_md, root_content):
        updated_files.append(layout.checkpoints_md.relative_to(cwd).as_posix())

    return SyncPhaseCheckpointsResult(
        generated=True,
        phase_count=len(grouped),
        checkpoint_dir=layout.phase_checkpoints_dir.relative_to(cwd).as_posix(),
        root_index=layout.checkpoints_md.relative_to(cwd).as_posix(),
        updated_files=updated_files,
        removed_files=removed_files,
    )
